---
title: "このブログについて"
date: 2021-12-10T06:26:00+09:00
draft: false
isCJKLanguage: true
categories:
    - szk302
tags:
    - szk302
---

= このブログについて

== プライバシーポリシー

当ブログでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。このGoogleアナリティクスはデータの収集のためにCookieを使用しています。このデータは匿名で収集されており、個人を特定するものではありません。 + 
この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。この規約に関しての詳細は https://marketingplatform.google.com/about/analytics/terms/jp/[Googleアナリティクスサービス利用規約] のページや https://policies.google.com/technologies/ads?hl=ja[Googleポリシーと規約] ページをご覧ください。

== 免責事項

当サイトからのリンクやバナーなどで移動したサイトで提供される情報、サービス等について一切の責任を負いません。 +
また当サイトのコンテンツ・情報について、できる限り正確な情報を提供するように努めておりますが、正確性や安全性を保証するものではありません。情報が古くなっていることもございます。 +
当サイトに掲載された内容によって生じた損害等の一切の責任を負いかねますのでご了承ください。 

== 第三者配信の広告サービスについて

当サイトは、第三者配信の広告サービス「Google Adsense（グーグルアドセンス）」を利用しています。

Googleなどの第三者広告配信事業者は、訪問者の興味に応じた広告を表示するために、Cookie（当サイトの訪問者が当サイトや他のサイトにアクセスした際の情報など）を使用することがあります。

訪問者は、広告設定で訪問者に合わせた広告（以下、「パーソナライズド広告」とします。）を無効にすることが出来ます。その設定をする場合は、 https://adssettings.google.com/authenticated[こちら] をクリックしてください。また、 https://www.aboutads.info[www.aboutads.info] にアクセスすれば、パーソナライズド広告に使われる第三者配信事業者の Cookie を無効にできます。

第三者配信による広告掲載を無効にしていない場合は、第三者配信事業者や広告ネットワークの配信する広告がサイトに掲載されることがあります。

Googleによって広告の第三者配信が認められている広告配信事業者の詳細は、 https://support.google.com/admanager/answer/94149[ここ] をクリックしてください。

== その他

* Amazonのアソシエイトとして、[Szk302 Teck Blog] は適格販売により収入を得ています。