version: "3"

services:
  content-workspace:
    build: ../environment/docker-images/hugo
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "../"
        target: "/workspace"