---
title: JUnitのxmlレポートをALLUREを使用してメール送信可能なHTMLレポート化する
date: 2022-10-16T07:54:00+09:00
draft: false
tags:
  - Allure
  - Allure Report
  - JUnit
---

= JUnitのxmlレポートをALLUREを使用してメール送信可能なHTMLレポート化する

メールでJUnitのテスト結果を知りたいという要望のため調査

Allure Reportはサーバが必要(HTML版含め)だったが、 https://github.com/fescobar/allure-docker-service[fescobar/allure-docker-service] の *Emailable Report* 機能を使用するとメール用の1枚のHTMLで生成できることがわかった。

NOTE:: HTMLレポートをカスタマイズできるようなのだけど時間がないためこちらを使用する

== 方法

`docker-compose up` で起動した後、 http://localhost:5050/allure-docker-service/emailable-report/render にアクセスしレポートを取得する。

NOTE:: */emailable-report/export* のパスもあるが、zip形式のため */emailable-report/render* を使用する

今回作成したdocker-composeは以下の通り。 https://github.com/fescobar/allure-docker-service[fescobar/allure-docker-service] のdocker-composeに起動待ちのヘルスチェック設定と *Emailable Report* の設定を追加

.docker-compose.yml
[source,yml]
----
include::docker-compose.yml[]
----

.ディレクトリ構成
----
.
├── docker-compose.yml
└── test-results
    ├── test1
    │   ├── TEST-sample.timeout.SampleTest1.xml
    │   └── TEST-sample.timeout.SampleTest2.xml
    └── test2
        └── TEST-sample.timeout.SampleTest2.xml
----

test-resultsはgradleで実行したjunitテストの結果。

xmlのあるディレクトリを `/app/allure-results` にマウントすることでレポートが生成される。

NOTE: test-resultsを指定しても生成されなれない。階層構造のディレクトリは対応していない。

== 手順

1. `docker-compose up -d`
2.  http://localhost:5050/allure-docker-service/emailable-report/render[http://localhost:5050/allure-docker-service/emailable-report/render] にアクセス

=== 取得したEmailable Report

++++
<iframe width="700" height="1150" srcdoc="&lt;html&gt; &lt;head&gt; &lt;title&gt;Myテストレポート - Allure Docker Service&lt;/title&gt; &lt;meta charset=&quot;utf-8&quot;&gt; &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt; &lt;link rel=&quot;stylesheet&quot; href=&quot;https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.css&quot;&gt; &lt;link rel=&quot;shortcut icon&quot; href=&quot;/static/favicon&quot;&gt; &lt;/head&gt; &lt;body&gt; &lt;div class=&quot;container jumbotron&quot;&gt; &lt;div class=&quot;display-4 lead&quot;&gt;Myテストレポート&lt;/div&gt; &lt;div class=&quot;lead&quot;&gt;Allure Docker Service&lt;/div&gt; &lt;br&gt; &lt;ul class=&quot;list-group&quot;&gt; &lt;li class=&quot;list-group-item d-flex justify-content-between align-items-center&quot;&gt; Project ID &lt;span class=&quot;badge badge-light badge-pill&quot;&gt; default &lt;/span&gt; &lt;/li&gt; &lt;li class=&quot;list-group-item d-flex justify-content-between align-items-center&quot;&gt; Server Link &lt;span class=&quot;badge badge-light badge-pill&quot;&gt; &lt;a href=&quot;https://www.szk302.dev/&quot; target=&quot;_blank&quot;&gt;https://www.szk302.dev/&lt;/a&gt; &lt;/span&gt; &lt;/li&gt; &lt;/ul&gt; &lt;br&gt; &lt;div class=&quot;table-responsive&quot;&gt; &lt;table class=&quot;table table-hover&quot;&gt; &lt;thead&gt; &lt;tr&gt; &lt;th scope=&quot;col&quot; class=&quot;table-active text-center&quot;&gt;Total&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;table-success text-center&quot;&gt;Passed&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;table-danger text-center&quot;&gt;Failed&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;table-warning text-center&quot;&gt;Broken&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;table-light text-center&quot;&gt;Skipped&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;table-dark text-center&quot;&gt;Unknown&lt;/th&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;tbody&gt; &lt;tr&gt; &lt;th scope=&quot;col&quot; class=&quot;text-center&quot;&gt;2&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;text-center&quot;&gt;1 (50.00%)&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;text-center&quot;&gt;1 (50.00%)&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;text-center&quot;&gt;0 (0.00%)&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;text-center&quot;&gt;0 (0.00%)&lt;/th&gt; &lt;th scope=&quot;col&quot; class=&quot;text-center&quot;&gt;0 (0.00%)&lt;/th&gt; &lt;/tr&gt; &lt;/tbody&gt; &lt;/table&gt; &lt;/div&gt; &lt;hr class=&quot;my-4&quot;&gt; &lt;div class=&quot;card border-secondary mb-3 border-success&quot;&gt; &lt;div class=&quot;card-header&quot;&gt; testSomeLibraryMethod() &lt;span class=&quot;badge badge-pill badge-success&quot;&gt;passed&lt;/span&gt; &lt;/div&gt; &lt;div class=&quot;card-body&quot;&gt; &lt;!-- CARD TEXT --&gt; &lt;p class=&quot;card-text&quot;&gt; &lt;b&gt;description:&lt;/b&gt; &lt;br&gt; &lt;b&gt;duration:&lt;/b&gt; 0.042 s &lt;br&gt; &lt;b&gt;severity:&lt;/b&gt; normal &lt;br&gt; &lt;b&gt;suite:&lt;/b&gt; sample.timeout.SampleTest1 &lt;br&gt; &lt;b&gt;testClass:&lt;/b&gt; sample.timeout.SampleTest1 &lt;br&gt; &lt;b&gt;package:&lt;/b&gt; sample.timeout.SampleTest1 &lt;br&gt; &lt;br&gt; &lt;/p&gt; &lt;!-- TABLE --&gt; &lt;/div&gt; &lt;/div&gt; &lt;div class=&quot;card border-secondary mb-3 border-danger&quot;&gt; &lt;div class=&quot;card-header&quot;&gt; testSomeLibraryMethod() &lt;span class=&quot;badge badge-pill badge-danger&quot;&gt;failed&lt;/span&gt; &lt;/div&gt; &lt;div class=&quot;card-body&quot;&gt; &lt;!-- CARD TEXT --&gt; &lt;p class=&quot;card-text&quot;&gt; &lt;b&gt;description:&lt;/b&gt; &lt;br&gt; &lt;b&gt;duration:&lt;/b&gt; 0.052 s &lt;br&gt; &lt;b&gt;severity:&lt;/b&gt; normal &lt;br&gt; &lt;b&gt;suite:&lt;/b&gt; sample.timeout.SampleTest2 &lt;br&gt; &lt;b&gt;testClass:&lt;/b&gt; sample.timeout.SampleTest2 &lt;br&gt; &lt;b&gt;package:&lt;/b&gt; sample.timeout.SampleTest2 &lt;br&gt; &lt;br&gt; &lt;/p&gt; &lt;!-- TABLE --&gt; &lt;/div&gt; &lt;/div&gt; &lt;/div&gt; &lt;/body&gt; &lt;/html&gt;">
</iframe>
++++

== 環境変数

Emailable Reportは環境変数で以下の設定変更が可能

EMAILABLE_REPORT_CSS_CDN:: レポートに使用されているCSSのCDNのURL
EMAILABLE_REPORT_TITLE:: レポートのタイトル
SERVER_URL:: Server Linkという部分のURL

== レポート表示時に使用されているリソースのURL

レポート表示時にダウンロードされるリソースのURLは以下の通り。

* https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.css
* https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700

== 参考

* https://github.com/fescobar/allure-docker-service[fescobar/allure-docker-service]
